## Welcome to the first notebook in Statistical Analaysis of Financial Data in Python

#### Pre-requisites:
1. Understanding of probability distribution
2. A little bit of stats

The things we gonn use later:
1. Expected value of a random variable\
2. Variance
3. Standard Deviation
4. Co-variance
5. Correlation

Let's say there is a random variable "X" whose value can be anything. Now let us say that I have muliple of these vaibles x = (X1, X2, X3 ..... Xd) upto d. Now the expected value of a random variable X is donated by E(X) is generally the mean of that variable represented by mu

In [28]:
import numpy as np
row_vector = 10*np.random.rand(3)


In [40]:
print(row_vector) # this is a row vector of a random variable
# what would be the variance of these row numbers
variances = ((row_vector - np.mean(row_vector))**2)                
print(variances)
# covariance = (row_vector - np.mean(row_vector))
# print(covariance)      

[8.63428235 0.44884549 4.12874989]
[17.89563358 15.64292481  0.07574019]


We can combine the above operation by making a varince-covariance matrix

In [39]:
matrix = np.outer(row_vector, row_vector)
print(matrix)

[[74.55083175  3.87545871 35.64879235]
 [ 3.87545871  0.20146228  1.85317078]
 [35.64879235  1.85317078 17.04657569]]


The diagonals of the above matrix are the variances and the rest are co-variances with respect to each other

### Time-Series data
Fininacial data is time series data that meand it is a function of time, x(t). \
Since, time is a continous data but the time we would be using can be discrete \

Such as at a given time t, we can define the the dependenc of some variable over past time as follows: \
xt  = f(…, xt−2, xt−1) + ϵt, 
where f is some function, possibly unknown, and ϵt is an unobservable random variable \
The random variable ϵt is a “residual”, an “error term”, or especially in time series applications, an “innovation”. We generally assume that the error term, as a random variable, has the following properties.
- For each t, the expected value of the error term is zero, that is, E(ϵt) = 0.
- For each t, the variance of the error term is constant, that is, V(ϵt) = σ2, where σ is some positive, but perhaps unknown, number.
- For each t and each h > 0, the correlation of two error terms is zero, that is, Cor(ϵt, ϵt+h) = 0.